- hosts: web
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      enabled: yes
      name: httpd